package com.bayu.instagramhomepage.ui.utils

object Data {

    val dummyDataPosts: List<Post> = listOf(
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x300",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x301",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x302",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x303",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x304",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x305",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x306",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x307",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x308",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x309",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x310",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x311",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x300",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x301",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x302",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x303",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x304",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x305",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x306",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x307",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x308",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x309",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x310",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x311",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x300",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x301",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x302",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x303",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x304",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x305",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x306",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x307",
        ),
        Post(
            TypePost.Shopping,
            "https://source.unsplash.com/random/300x308",
        ),
        Post(
            TypePost.Video,
            "https://source.unsplash.com/random/300x309",
        ),
        Post(
            TypePost.Collections,
            "https://source.unsplash.com/random/300x310",
        ),
        Post(
            TypePost.Default,
            "https://source.unsplash.com/random/300x311",
        ),
    )
}

data class Post(
    val typePost: TypePost,
    val image: String,
)